### ISSUE TITLE
Container width jumping between Nationality and Personal Details tabs

### ISSUE THREAD

**Issue by tatyree** [JudicialAppointmentsCommission/application-form#23]
On DOM1 machines - any modern browser - the container width expands when moving from Nationality to Personal Details.  It isn't clear why and I am not able to reproduce this on OSX, but I have seen it on Chrome on a JAC windows machine and have reports that it does the same on firefox. 

A quick look at the HTML and CSS doesn't reveal anything obvious.

**Comment by tatyree** [comment]
This is almost certainly down to the way windows adds scrollbars.

**Comment by ollietreend** [comment]
This is caused by the Nationality page not requiring a scrollbar, whereas the Personal Details page is long enough to require one.

Thus, when moving between these two pages, the scrollbar is shown/hidden causing the page to be thrown 'off centre' when the scrollbar appears (since the viewport gets slightly narrower to accommodate  for the scrollbar).

This is standard behaviour and therefore I'm of the opinion that it doesn't need 'fixing'.

However, if this behaviour does prove problematic, there is a very simple and well established workaround [documented on CSS-Tricks](https://css-tricks.com/eliminate-jumps-in-horizontal-centering-by-forcing-a-scroll-bar/) – essentially it involves forcing a scrollbar to always show, even when not required.

**Comment by tatyree** [comment]
Default browser behaviour.  Closing.
